//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int id { get; set; }
        public Nullable<int> box_number { get; set; }
        public string black_id { get; set; }
        public string grey_id { get; set; }
        public string location_x { get; set; }
        public string location_y { get; set; }
        public string location_z { get; set; }
        public string block { get; set; }
        public string red_id { get; set; }
    }
}
