//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_proposal
    {
        public int id { get; set; }
        public string cp_id { get; set; }
        public string cp_date { get; set; }
        public Nullable<int> version { get; set; }
        public string delivery_type { get; set; }
        public string rw { get; set; }
        public string air { get; set; }
        public string po_id { get; set; }
        public string po_date { get; set; }
        public string order_id { get; set; }
        public string order_date { get; set; }
        public string ct_id { get; set; }
        public string ct_date { get; set; }
        public string customer { get; set; }
        public string project { get; set; }
    }
}
