//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_details
    {
        public int id { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string port_name { get; set; }
        public string final_destination { get; set; }
    }
}
