//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int id { get; set; }
        public string id_contract { get; set; }
        public string date { get; set; }
        public string delivery_type { get; set; }
        public string id_cp { get; set; }
        public string client_order_id { get; set; }
        public string id_order { get; set; }
        public string delivery_point { get; set; }
        public string cp_version { get; set; }
        public string customer { get; set; }
        public Nullable<double> amount { get; set; }
        public string cp_date { get; set; }
        public string client_order_id_date { get; set; }
        public string id_order_date { get; set; }
    }
}
