//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_in_boxes
    {
        public int id { get; set; }
        public Nullable<int> box_numb { get; set; }
        public string part_name { get; set; }
        public string part_code { get; set; }
        public string amount { get; set; }
        public string net { get; set; }
        public string gross { get; set; }
        public string id_order { get; set; }
        public string black_id { get; set; }
        public string pl_id { get; set; }
        public string pl_date { get; set; }
        public string invoice_id { get; set; }
        public string invoice_date { get; set; }
    }
}
