//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_in_contract
    {
        public int id { get; set; }
        public string id_contract { get; set; }
        public string item_code { get; set; }
        public string name { get; set; }
        public string quantity { get; set; }
        public string unit_price { get; set; }
        public string amount_price { get; set; }
    }
}
