//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_in_cp
    {
        public int id { get; set; }
        public string part_code { get; set; }
        public string part_name { get; set; }
        public string hs_code { get; set; }
        public string quantity { get; set; }
        public string unit_price { get; set; }
        public string amount_price { get; set; }
        public string cp_id { get; set; }
        public string percentage { get; set; }
        public string weight_of_item { get; set; }
        public string price_rw { get; set; }
        public string price_air { get; set; }
        public string production_time { get; set; }
        public string delivery_air { get; set; }
        public string delivery_rw { get; set; }
        public Nullable<int> version { get; set; }
    }
}
