//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class official_letters
    {
        public int id { get; set; }
        public string letter_id { get; set; }
        public string letter_date { get; set; }
        public string company_name { get; set; }
        public string letter_text { get; set; }
    }
}
