//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItem
    {
        public int id { get; set; }
        public Nullable<int> id_item { get; set; }
        public string part_code { get; set; }
        public string name { get; set; }
        public Nullable<int> amount { get; set; }
        public string id_order { get; set; }
        public int version { get; set; }
        public string version_date { get; set; }
        public string remarks { get; set; }
    }
}
