//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string id_order { get; set; }
        public string customer_order_id { get; set; }
        public string dz_date { get; set; }
        public string c_date { get; set; }
        public string descr { get; set; }
        public int version { get; set; }
        public string com_proposal { get; set; }
        public string contract { get; set; }
        public string remarks { get; set; }
        public string com_proposal_date { get; set; }
        public string contract_date { get; set; }
    }
}
